<?php
$GLOBALS["botyer"]="bwin";
$GLOBALS["mackodu"]="hitit";
$GLOBALS["menu"]="2";
$GLOBALS["kisaad"]="kisaad";
$GLOBALS["bulten"]="hitit";
$GLOBALS["tema"]="dark-theme";
$GLOBALS["canli_kapali"]="0";
$GLOBALS["canli_kapali_aciklama"]="";
$GLOBALS["site_kapali"]="0";
$GLOBALS["site_kapali_aciklama"]="";
$GLOBALS["pay_token"]="ueEwLJtPS8VlxTsFoIZU8o92OIzmKPXm";
$GLOBALS["pay_secret"]="CBmJbaBtlA37kv8T2XfcqQVVtEumGFsQ";